config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/apods')

  resources :apods, constraints: { id: /\d{4}-\d{2}-\d{2}/ },
                    only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/400', to: 'errors#bad_request', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/apod.rb
# encoding: utf-8

require 'faraday'
require 'faraday_middleware'

class Apod < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 200 }
  validates :explanation, presence: true, length: { maximum: 5000 }
  validates :url, presence: true, length: { maximum: 200 }
  validates :hdurl, length: { maximum: 200 }
  validates :media_type, presence: true, length: { maximum: 100 }
  validates :date, presence: true, uniqueness: true
  validates :copyright, length: { maximum: 100 }

  def self.searched(search)
    where('LOWER(title) LIKE LOWER(?) OR LOWER(explanation) LIKE LOWER(?)',
          "%#{search}%", "%#{search}%")
  end

  def self.find_for_date(date)
    apod = Apod.find_by(date: date)
    unless apod
      apod = Apod.new(date: date)
      apod.fetch_data
      apod.save
    end
    apod
  end

  def previous
    earliest_apod = Date.new(1995, 06, 16)
    Apod.find_for_date(date.yesterday) if date.yesterday >= earliest_apod
  end

  def next
    Apod.find_for_date(date.tomorrow) if date.tomorrow <= Date.today
  end

  def fetch_data
    connection = Faraday.new build_url do |conn|
      conn.response :json, content_type: /\bjson$/
      conn.adapter Faraday.default_adapter
    end

    response = connection.get
    handle_possible_errors(response)

    data = response.body
    data.delete('service_version')

    self.attributes = data
  end

  def image?
    media_type == 'image'
  end

  def formatted_date
    date.to_s
  end

  def to_param
    formatted_date
  end

  private

  def handle_possible_errors(api_response)
    if rate_limit_reached?(api_response)
      raise RateLimitReachedError, 'Das RateLimit wurde erreicht. Versuchs '\
                                   'doch gleich nochmal'
    end

    code = api_response.body['code']

    if code
      if code == 400
        raise ImpossibleApodError, 'Dieses Datum liegt außerhalb der ' \
                                   'erlaubten Datumsgrenzen.'
      end

      if code > 400
        raise ApodNotFoundError, 'Dieser Apod konnte nicht geladen werden.'
      end
    end
  end

  def build_url
    api_key = Rails.application.secrets[:nasa_api_key]
    "https://api.nasa.gov/planetary/apod?api_key=#{api_key}" \
      "&date=#{formatted_date}&hd=true"
  end

  def rate_limit_reached?(api_response)
    remaining = api_response.headers['x-ratelimit-remaining'].to_i
    remaining == 0
  end
end

app/controllers/apods_controller.rb
class ApodsController < ApplicationController
  def index
    load_apod(Date.today)
  end

  def show
    load_apod(Date.parse(params[:id]))
  end

  def search
    @apods = Apod.searched(params[:search]).paginate(page: params[:page])
    @search_term = params[:search]
  end

  private

  def load_apod(date)
    @apod = Apod.find_for_date(date)
    @next_apod = @apod.try(:next)
    @previous_apod = @apod.try(:previous)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  before_action { @exception = env['action_dispatch.exception'] }

  [:not_found, :bad_request, :internal_server_error].each do |type|
    define_method type do
      respond_to do |format|
        format.html { render status: type }
        format.any { head type }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apods/_apod.html.haml
.apod-information-container
  .apod-container-inner
    %h2= @apod.title
    - unless @apod.copyright.blank?
      .copyright
        %span.glyphicon.glyphicon-copyright-mark{aria: {hidden: "true"}}
        = @apod.copyright

    .apod-explanation= @apod.explanation

.apod-media-container
  .apod-container-inner
    - if @apod.image?
      %img.apod-media-item{src: @apod.url}
    - else
      %iframe.apod-media-item-other{src: @apod.url}

app/views/apods/index.html.haml
= render "apod"

app/views/apods/search.html.haml
%h1 Suchergebnisse für "#{@search_term}"
%ul
  - @apods.each do |apod|
    %li= link_to "#{apod.title} (#{apod.formatted_date})", apod

= will_paginate @apods

app/views/apods/show.html.haml
= render "apod"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title AstroPics
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body

  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button{type: 'button', class: 'navbar-toggle collapsed',
                data: {toggle: 'collapse', target: '#bs-navbar-collapse'},
                aria: {expanded: false}}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: '/'} APOD

      .collapse.navbar-collapse{id: 'bs-navbar-collapse'}
        = form_tag search_apods_path, method: 'get',
                                      class: 'navbar-form navbar-right',
                                      role: 'search' do
          = text_field_tag :search, params[:search], id: 'js-search-input'
          = submit_tag 'Suchen', name: nil, class: 'btn btn-primary'

        %ul.nav.navbar-nav.navbar-left
          - if @previous_apod
            %li
              = link_to 'Früher', @previous_apod,
                id: 'js-previous-apod'
          - if @next_apod
            %li
              = link_to 'Später', @next_apod, id: 'js-next-apod'

  .container
    - if flash[:error]
      .alert.alert-warning{role: 'alert'}
        = flash[:error]

    = yield

app/views/layouts/errors.html.haml
.container
  .row
    .col-md-12
      = yield

      = @exception